language: java
sudo: false

jdk:
  - openjdk11

script: ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    urls:
      - secure: "1u0hicbRywUTYGzKPq7awMK0taYj76nnul0UWTsfor/qEyE1ozHiMUj5u/0sXjK81q/uDotaX2S2M/s8cxV3LXzdUiPWOiXE1h+r7o/Sjm7NoOrsLSyHtFpquWcgJHRQTLay4hAwPH5yUAjuyw5gan+LeUet9ljdQ3TtuZDOS3w="
    on_start: always
